travis:
  secure:
    BINSTAR_TOKEN: RY5w7smIbgt43YSh+6h9pKeDjVVu2u9GQrcnPw7WvJld1XZ8BMieJaBbGsCe1N0oWJg77UAD0E+o5cbzcg/pHM9FoOZODJPtHx1N9EqYKP+87aWLiSZqFQSzjM+y5t6NLRlFRBlFHUhzo5JIKaC0k6cCZFZw7wwB57uX8G3OUTRZ0m4Tu9/1goNbAmizEB0zU3WdZQa1rFcri6yJC1lplK2gS3RLBWvvvbLKKLA8cvYg0jPkUJVbB9Xr1cwQf1qhc+8Xrkjfigd2P8OAm6SN44C9Kk9UR6BRc4UBA8zd7LO3lNkQJwVFPemuSQ65R+oPWE6wo9SOzAxQy1Ssw/D2Q7GGgva0e7iB5iXaBhX7Ukha4qcbjMU8LUt2d4TbarWWY7CJ+8x4PnhewnlqS37y05XDJzNzipQ9v1z7B+rwFhoJnNlE7ytx2lfPsbv0wR8gsWhvwGUPudnLcLuVOJiBU6J5ul/Uy2d1Sc6F1q43Hk0O8awGyrLtGWin7Hqu4T5PHEt+3dXFQ4ta9GH0eb/BN4KlS5Msn8i9eAhnjPmnl1M6hH987+QVkcnmcNpOYXfji4xLs54u1Ak0R8UHTjfxKFgqyEwbbx8+ya0+FNVKPYWtY5s4oKl2yFRVzX5F+L3dCsEMqtSZgiAQg0+M847mldSMlvc80t91FuC2bh9NKpM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
